### ISSUE TITLE
android.content.res.Resources$NotFoundException: Resource ID #0x0

### ISSUE THREAD

**Issue by mslinn** [anismiles/websocket-android-phonegap#6]
I created an Eclipse Android project called websocket-android-phonegap; when debugging I got this:
`android.content.res.Resources$NotFoundException: Resource ID #0x0`
Looks like index.html is not found; I stripped out everything inside it and the error happens right after this line is executed:

``` super.loadUrl("file:///android_asset/www/index.html");```
I zipped up the project in case anyone wants to look at it
http://slinnbooks.com/mslinn-websocket-android-phonegap.zip

It's probably something stupid, but I don't see it.
```

**Comment by sagetarian** [comment]
i'm also having this issue...

**Comment by sagetarian** [comment]
http://marguspala.com/basic-phonegap-android-app-from-scratch-step-by-step/

pay attention to point 6... my issue was i forgot to copy those xml files into the /res folder

mine works now

**Comment by kevingo** [comment]
It occurs the same issue for me. To solve it, just copy the xml folder to /res.

**Comment by mkhuda** [comment]
its appear to my phonegap app ! ill try to fix this again
